internal/dms/service/user.go
internal/dms/storage/op_permission_verify.go

fix: permission are not available when roles are disabled

---

build/dms.spec
config.yaml
database_driver_option.yaml
internal/apiserver/conf/options.go
internal/dms/biz/db_service.go
internal/dms/service/cloudbeaver.go
internal/dms/service/service.go

merge the configuration file database_driver_options.yaml

---

internal/dms/biz/cloudbeaver.go
internal/dms/service/cloudbeaver.go
internal/dms/storage/cloudbeaver.go

fix: cloudbeaver

---

internal/dms/biz/db_service.go

trigger sync after manipulate db_service

---

api/swagger.json
api/swagger.yaml
internal/dms/pkg/constant/const.go
internal/dms/service/db_service.go
internal/dms/service/member.go
internal/dms/service/member_group.go
internal/dms/service/role.go
internal/dms/service/user.go
internal/dms/storage/db_service.go
internal/dms/storage/storage.go
pkg/dms-common/api/dms/v1/db_service.go

https://github.com/actiontech/dms/issues/78

Db fuzzy keyword

---

internal/dms/biz/cloudbeaver.go
internal/dms/pkg/constant/const.go
internal/pkg/cloudbeaver/cloudbeaver.go
internal/pkg/cloudbeaver/graphql.go
internal/pkg/cloudbeaver/model/models_gen.go
internal/pkg/cloudbeaver/resolver/executor_gen.go
internal/pkg/cloudbeaver/resolver/service.sql_gen.go
internal/pkg/cloudbeaver/schema/service.auth.graphqls
internal/pkg/cloudbeaver/schema/service.sql.graphqls

cloudbeaver upgrade 

---

build/dms.spec
build/service-file-template/dms.systemd

the dms service specifies the running user

---

build/dms.spec

the rpm upgrade installation retains the original configuration file

---

internal/dms/biz/db_service.go
pkg/dms-common/dmsobject/plugin.go

validate db_service data before deletion

---

pkg/dms-common/dmsobject/db_service.go

issues-108: request data source list query parameter encoding

---

internal/dms/service/member_group.go
internal/dms/storage/db_service.go

issues-103: clear associated data after deleting a data source

---

internal/dms/pkg/constant/const.go

issues-114: add db2, TDSQL For InnoDB,  TiDB type case conversion

---

api/dms/service/v1/license.go
api/swagger.json
api/swagger.yaml
internal/apiserver/middleware/license.go
internal/apiserver/middleware/license_qa.go
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
internal/dms/biz/db_service.go
internal/dms/biz/license.go
internal/dms/biz/license_qa.go
internal/dms/service/license.go
internal/dms/service/service.go
internal/dms/storage/db_service.go
internal/dms/storage/license_qa.go
internal/dms/storage/model/model.go
internal/dms/storage/storage.go
pkg/dms-common/api/dms/v1/router.go

dms支持license授权访问

---

internal/apiserver/service/router.go

https://github.com/actiontech/sqle-ee/issues/1282

support authorization by cookie

---

internal/dms/pkg/constant/const.go

https://github.com/actiontech/dms-ee/issues/84

fix: SQL Server DBType name don‘t match with sqle plugin

---

internal/dms/service/member.go

https://github.com/actiontech/dms/issues/113

fix: project manager field display error

---

config.yaml
internal/apiserver/conf/options.go
internal/dms/service/service.go
internal/dms/storage/model/model.go
internal/dms/storage/storage.go

#120 
https://github.com/actiontech/dms/issues/126

fix: limit structure column length

---

internal/dms/biz/cloudbeaver.go

issues-131: 用户对数据源的无查询权限，但是能在工作台看到

---

.github/workflows/check-pr-files.yml

Issue-https://github.com/actiontech/dms-ee/issues/81: add check file due to the addition of ee file (internal/data_masking/biz/data_masking_conf_ee.yml)

actiontech/dms-ee/issues/81: 增加检查文件，使得dms ee上能添加ee.yml文件

---

config.yaml

[issues](https://github.com/actiontech/dms-ee/issues/94)

issues-94: dms default port changed to 10000

---

config.yaml
internal/apiserver/service/service.go
internal/dms/biz/cluster.go
internal/dms/biz/cluster_ce.go
internal/dms/biz/license.go
internal/dms/service/service.go
internal/dms/storage/cluster.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go
pkg/dms-common/conf/options.go

https://github.com/actiontech/dms-ee/issues/75

issues-75: dms support cluster

---

internal/dms/storage/storage.go

issues-141: disable foreign key constraint when migrating

---

api/dms/service/v1/db_service.go
api/swagger.json
api/swagger.yaml
internal/dms/biz/db_service.go
internal/dms/pkg/constant/const.go
pkg/dms-common/api/dms/v1/user.go

https://github.com/actiontech/dms-ee/issues/121

fix: database service tips

---

internal/dms/storage/user.go

issues-136: delete user associate data

---

config.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/service.go
internal/dms/biz/data_export_workflow.go
internal/dms/biz/data_export_workflow_ce.go
internal/dms/service/data_export_workflow.go
internal/dms/service/service.go
pkg/dms-common/conf/options.go

https://github.com/actiontech/dms-ee/issues/134

issues-134: file download in cluster mode

---

api/dms/service/v1/data_export_task.go
internal/dms/biz/data_export_task.go
internal/dms/biz/repo_fields.go
internal/dms/service/data_export_workflow.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go

https://github.com/actiontech/dms-ee/issues/137

feat: add export sql type

---

api/swagger.json
api/swagger.yaml
internal/dms/biz/data_export_task.go
internal/dms/storage/data_export_task.go
internal/dms/storage/model/model.go

https://github.com/actiontech/dms-ee/issues/157

Issue 157 ce

---

internal/dms/biz/proxy.go

https://github.com/actiontech/sqle/issues/2238

feat: support rewrite url begin with /webhook/

---

internal/dms/service/data_export_workflow.go

https://github.com/actiontech/dms-ee/issues/112

fix:time error

---

config.yaml

issues-172: change the host default to 127.0.0.1

---

api/dms/service/v1/license.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
internal/dms/biz/license_qa.go
internal/dms/biz/user.go
internal/dms/service/license.go
internal/dms/storage/db_service.go
internal/dms/storage/user.go

[关联issues](https://github.com/actiontech/dms-ee/issues/170)

issues-170: licence usage statistics

---

internal/dms/biz/cloudbeaver.go

https://github.com/actiontech/dms-ee/issues/98

fix: admin can use connections to all dbs

---

internal/pkg/cloudbeaver/cloudbeaver.go

https://github.com/actiontech/dms/issues/182

fix: modify CB version interface inheritance order

---

internal/dms/biz/cloudbeaver.go
internal/pkg/cloudbeaver/graphql.go

issues-164: cloudbeaver audit using associated data source rule template

---

internal/dms/biz/data_export_workflow.go

https://github.com/actiontech/dms-ee/issues/145

issues-145: add workflow export event action

---

api/dms/service/v1/configuration.go
internal/dms/service/configuration.go

modify: return of oauth2 configuration add a param

---

internal/dms/biz/cloudbeaver.go

https://github.com/actiontech/dms/issues/188

fix: duplicate valid session cookies

---

api/dms/service/v1/configuration.go

actiontech/dms-ee#190 
1. 取消对state为必须参数的校验

modify: cancle validation of param state

---

pkg/dms-common/api/dms/v1/webhooks.go

https://github.com/actiontech/sqle/issues/2268

Fix issue2268

---

internal/dms/storage/model/model.go

[#198 ](https://github.com/actiontech/dms-ee/issues/198)

modify: change type of third_party_user_info in storage

---

internal/apiserver/service/dms_controller.go

https://github.com/actiontech/dms-ee/issues/204

fix: chinese file names cause garbled characters

---

internal/dms/biz/cloudbeaver.go
internal/dms/pkg/constant/const.go

#207
actiontech/dms/issues/207
cloudbeaver使用mysql驱动连接goldendb类型数据库，新增goldendb数据源后，可在cloudbeaver中进行查看、审核等操作

cloudbeaver适配goldendbl类型链接

---

Makefile
api/dms/service/v1/db_service.go
api/dms/service/v1/masking.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
internal/dms/biz/cloudbeaver.go
internal/dms/biz/cloudbeaver_ce.go
internal/dms/biz/db_service.go
internal/dms/biz/masking.go
internal/dms/biz/masking_ce.go
internal/dms/biz/repo_fields.go
internal/dms/service/cloudbeaver.go
internal/dms/service/db_service.go
internal/dms/service/masking.go
internal/dms/service/service.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go
pkg/dms-common/api/dms/v1/db_service.go

https://github.com/actiontech/dms-ee/issues/207

actiontech/dms-ee/issues/207: masking rules, masking configure

---

internal/apiserver/service/router.go

https://github.com/actiontech/dms/issues/118

fix: fixed missing routing causing static resources to be returned

---

api/dms/service/v1/masking.go
api/swagger.json
api/swagger.yaml
internal/dms/biz/masking.go
internal/dms/service/masking.go

https://github.com/actiontech/dms-ee/issues/207

data masking out

---

api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
pkg/dms-common/api/dms/v1/user.go

接口定义
https://github.com/actiontech/sqle/issues/2309

Fix issue2309

---

internal/apiserver/service/router.go

fix: add skip rule for user bind page

---

internal/apiserver/service/router.go

modify: skip jwt authentication with request path prefix /webhook/

---

api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
pkg/dms-common/api/dms/v1/project.go

chore: projects import api define

---

api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go

chore:change api method to post

---

api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go

chore:change put to post , because import no need update

---

api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml

fix:struct response should use model type

---

api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go

fix:swagger error

---

pkg/dms-common/api/dms/v1/user.go

[关联issues](https://github.com/actiontech/sqle/issues/2340)

变更操作类型默认值为未知操作类型

---

api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
pkg/dms-common/api/dms/v1/project.go

chore:add business id

---

api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml

chore:export api define add filter param

---

internal/dms/biz/access_token.go
pkg/dms-common/api/accesstoken/access_token.go
pkg/dms-common/api/jwt/jwt.go

add get token from context func

---

internal/dms/biz/op_permission.go
internal/dms/biz/role.go
internal/dms/pkg/constant/const.go
internal/dms/service/user.go
pkg/dms-common/api/dms/v1/user.go

https://github.com/actiontech/sqle-ee/issues/1461

add optimization permission

---

api/dms/service/v1/cb_operation_logs.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go

工作台SQL操作记录

---

api/dms/service/v1/cb_operation_logs.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go

issue-256-api-1

---

api/dms/service/v1/cb_operation_logs.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go

工作台审计日志tips接口定义

---

internal/dms/storage/model/model.go

chore:operation log model define

---

api/dms/service/v1/cb_operation_logs.go
internal/apiserver/service/dms_controller.go
internal/dms/biz/cb_operation_log.go
internal/dms/biz/cb_operation_log_ce.go
internal/dms/biz/cloudbeaver.go
internal/dms/biz/cloudbeaver_ce.go
internal/dms/biz/repo_fields.go
internal/dms/service/cb_operation_log.go
internal/dms/service/cb_operation_log_ce.go
internal/dms/service/cloudbeaver.go
internal/dms/service/service.go
internal/dms/storage/cb_operation_log.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go
internal/pkg/cloudbeaver/graphql.go

记录下发sql的审计日志

---

internal/apiserver/service/router.go

https://github.com/actiontech/dms/issues/244

[feature] enable gzip encode in http for speed up static file transfer

---

internal/dms/storage/cb_operation_log.go

fix:order by desc

---

internal/dms/biz/cloudbeaver.go

https://github.com/actiontech/dms-ee/issues/276

fix: add allowPublicKeyRetrieval params for cb connect to mysql8

---

internal/apiserver/service/dms_controller.go
internal/dms/biz/cb_operation_log.go
internal/dms/biz/cloudbeaver.go
internal/dms/biz/cloudbeaver_ce.go
internal/dms/service/cb_operation_log.go
internal/dms/service/cb_operation_log_ce.go
internal/dms/storage/cb_operation_log.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go
internal/pkg/cloudbeaver/graphql.go

Issue 256 9

---

internal/dms/biz/cloudbeaver.go
internal/dms/biz/cloudbeaver_ce.go

修复当SQL审核未开启时,审计日志不新增记录的问题

---

api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go

数据源批量导入接口定义

---

api/dms/service/v1/db_service.go
api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml

update DBServices import api docs

---

api/dms/service/v1/db_service.go
api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go

update api for importing db services and testing db services connection

---

api/dms/service/v1/db_service.go
api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go

Import db service api fix

---

pkg/periods/periods.go
pkg/periods/periods_test.go

add unit test for periods

---

internal/dms/storage/model/model.go

https://github.com/actiontech/sqle-ee/issues/1597
描述：
指定字段类型

Specifying Field Types

---

api/dms/service/v1/db_service.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
internal/dms/service/db_service.go

https://github.com/actiontech/dms-ee/issues/312

全局数据源总览新增接口

---

api/dms/service/v1/db_service.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
internal/dms/biz/db_service.go
internal/dms/service/db_service.go
internal/dms/service/db_service_ce.go
internal/dms/storage/db_service.go

https://github.com/actiontech/dms-ee/issues/312
- 简化查询全局数据源接口请求、响应结构
- 新增查询全局数据源tips接口
- 数据源storage层实现 GetFieldDistinctValue 能力（给tips接口ee的实现用）

Feat overview of global db services ce

---

api/dms/service/v1/db_service_sync_task.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go

https://github.com/actiontech/dms-ee/issues/322

Interface Definition ：database synchronization task api group

---

api/dms/service/v1/db_service_sync_task.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go

https://github.com/actiontech/dms-ee/issues/322

API Definition: modify Swagger comments 

---

api/swagger.json
api/swagger.yaml
internal/dms/biz/db_service.go
internal/dms/service/db_service.go
pkg/dms-common/api/dms/v1/db_service.go

关联issue：https://github.com/actiontech/sqle-ee/issues/1576
数据源列表展示数据源绑定的实例扫描任务类型

Instance list add audit plan type

---

internal/dms/biz/cloudbeaver.go
internal/dms/pkg/constant/const.go

cb工作台同步tbase数据源
https://github.com/actiontech/sqle-ee/issues/1659

cb add tbase

---

api/swagger.json
api/swagger.yaml
pkg/dms-common/api/dms/v1/db_service.go

Intsance list audit plan api define modify

---

Makefile

https://github.com/actiontech/sqle-ee/issues/1687

Only use the version number to name the rpm package when publishing.

---

internal/dms/storage/convert.go

https://github.com/actiontech/sqle-ee/issues/1732
- 避免删除操作日志数据源、操作人后panic，对应列会显示空
> [!TIP]

fix CbOperationLog panic when del the dbService or operator

---

internal/dms/biz/cloudbeaver.go
internal/dms/biz/cloudbeaver_ce.go

https://github.com/actiontech/dms-ee/issues/308

修复 SQL工作台点击数据源列表查看数据时脱敏失效 

---

internal/dms/biz/op_permission.go
internal/dms/biz/role.go
internal/dms/pkg/constant/const.go
internal/dms/service/user.go
pkg/dms-common/api/dms/v1/user.go

关联issue：https://github.com/actiontech/sqle/issues/2564

modify: add op permission for creating pipeline

---

internal/dms/storage/convert.go
internal/dms/storage/model/model.go

https://github.com/actiontech/sqle/issues/2595
删除弃用字段和旧数据兼容逻辑

incompatible, del deprecated fields

---

pkg/dms-common/pkg/http/http.go

issue:
https://github.com/actiontech/sqle-ee/issues/1893
功能实现：
支持httpCient自定义超时时间
link：https://github.com/actiontech/sqle-ee/pull/1894

support http client with timout context

---

api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
pkg/dms-common/api/dms/v1/project.go

issue：https://github.com/actiontech/sqle/issues/2675
1. api定义，增加项目优先级字段到创建、更新和获取项目的http api、
2. 优先级分为三种：高优先级、中优先级和低优先级

api definition: add project priority in create update and get project api

---

api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
pkg/dms-common/api/dms/v1/project.go

issue: https://github.com/actiontech/sqle/issues/2675
assign in @ColdWaterLW 
1. 使得swagger中的api定义是enum的

api definition: make ProjectPriority enum in swagger

---

internal/dms/biz/project.go
internal/dms/biz/project_ce.go
internal/dms/service/project.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go
pkg/dms-common/api/dms/v1/project.go

assign in @ColdWaterLW 
link https://github.com/actiontech/dms-ee/pull/381
issue：https://github.com/actiontech/sqle/issues/2675
实现方案与接口测试：https://github.com/actiontech/sqle/issues/2675#issuecomment-2413205979
1. 创建、更新、获取项目列表，增加了项目优先级参数
2. 默认优先级为：中，兼容老版本数据。
3. 项目表增加字段：优先级
4. 对于其他创建项目方法，目前不支持配置优先级，暂时设置优先级为中，为此：增加了todo
详情请看原issue实现方案

project api group: support priority of project

---

api/swagger.json
api/swagger.yaml
internal/dms/biz/repo_fields.go
internal/dms/service/db_service.go
internal/dms/service/project.go
internal/dms/storage/storage.go
pkg/dms-common/api/dms/v1/db_service.go
pkg/dms-common/api/dms/v1/project.go
pkg/dms-common/dmsobject/db_service.go
pkg/dms-common/dmsobject/project.go

issue https://github.com/actiontech/sqle/issues/2675
test https://github.com/actiontech/sqle/issues/2675#issuecomment-2415964593
1. 查询数据源列表和项目列表的接口，增加了批量根据id查询的参数
2. 优化了dms common中调用上述数据源列表和项目列表的接口两个接口的函数
3. gormWhereCondition函数（用户构建gorm对象，增加语句），支持了in子句的添加
4. 增加了根据项目优先级筛选项目
添加了新参数，不影响旧版本接口调用

batch filter db service and project by id list

---

api/dms/service/v1/db_service.go
api/swagger.json
api/swagger.yaml
pkg/dms-common/api/dms/v1/db_service.go

issue: https://github.com/actiontech/sqle-ee/issues/1956
1. 创建、更新和获取数据源增加开启备份字段
2. 获取数据源列表，增加了数据源开启备份的字段

api definition: create update and get db service add param enable backup

---

api/dms/service/v1/db_service.go
api/dms/service/v1/project.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
pkg/dms-common/api/dms/v1/db_service.go

link https://github.com/actiontech/sqle/pull/2744

Sqle ce 2752

---

api/dms/service/v1/db_service.go
api/swagger.json
api/swagger.yaml
pkg/dms-common/api/dms/v1/db_service.go

chore:add status enum response

---

api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go

修改swagger命名定义
link https://github.com/actiontech/dms/pull/326

chore:rename id and desc

---

api/swagger.json
api/swagger.yaml
pkg/dms-common/api/dms/v1/db_service.go

增加状态枚举类型,写漏了
link https://github.com/actiontech/dms/pull/326

fix:add status type

---

internal/apiserver/service/dms_controller.go
internal/dms/biz/db_service.go
internal/dms/biz/repo_fields.go
internal/dms/service/db_service.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go
internal/dms/storage/storage.go

Sqle ce 2752 5

---

pkg/dms-common/dmsobject/db_service.go

修复url转译错误
https://github.com/actiontech/dms/issues/330

fix:twice escape filter_by_business field

---

internal/dms/biz/db_service.go
internal/dms/service/db_service.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go

assign in @ColdWaterLW 
https://github.com/actiontech/sqle-ee/issues/1956
测试 https://github.com/actiontech/sqle-ee/issues/1956#issuecomment-2475953094
1. 支持在数据源上标记开启备份

feat: support mark instance enable backup

---

api/dms/service/v1/db_service.go
api/swagger.json
api/swagger.yaml
pkg/dms-common/api/dms/v1/db_service.go

assign in @iwanghc 
issue https://github.com/actiontech/sqle-ee/issues/2028

api definition: add backup max rows for db service

---

internal/dms/biz/db_service.go
internal/dms/biz/plugin.go
internal/dms/service/db_service.go
internal/dms/service/plugin.go
internal/dms/storage/convert.go
pkg/dms-common/api/dms/v1/plugin.go
pkg/dms-common/dmsobject/plugin.go
pkg/params/params.go

remove unused plugin model

---

api/swagger.json
api/swagger.yaml
internal/dms/biz/db_service.go
internal/dms/service/db_service.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go

link https://github.com/actiontech/dms-ee/pull/416
https://github.com/actiontech/sqle-ee/issues/2028
1. 数据源增加备份最大行数可配置项

feat: db service add param backup max rows

---

internal/apiserver/service/router.go
internal/dms/biz/db_service.go
internal/dms/biz/plugin.go
internal/dms/pkg/errors/error.go
internal/dms/service/db_service.go
internal/dms/service/op_permission.go
internal/dms/service/proxy.go
internal/dms/service/user.go
pkg/dms-common/api/dms/v1/proxy.go

cherry-pick : https://github.com/actiontech/dms/issues/297

Log optimization

---

internal/dms/biz/cloudbeaver.go
internal/dms/biz/db_service.go
internal/dms/storage/model/model.go
internal/pkg/cloudbeaver/graphql.go

- 关联issue
https://github.com/actiontech/sqle-ee/issues/2011
- 描述
对于审核是否执行根据`allowQueryWhenLessThanAuditLevel`进行判断

fix: 修复sql工作台最高审核等级参数不生效的问题

---

internal/apiserver/cmd/server/main.go
internal/apiserver/service/service.go

issue: https://github.com/actiontech/dms-ee/issues/421

add service startup log

---

api/dms/service/v1/configuration.go
api/dms/service/v1/session.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
internal/dms/biz/oauth2_configuration.go
internal/dms/biz/oauth2_configuration_ce.go
internal/dms/biz/user.go
internal/dms/service/configuration.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go

https://github.com/actiontech/sqle-ee/issues/2029
https://github.com/actiontech/sqle-ee/issues/2030
OAuth2注销、OAuth2自动创建用户的默认密码可配置功能ce部分的实现
表变更：
1. 用户表新增idtoken字段，用于OAuth2对接中的注销流程
2. OAuth2配置表新增自动创建用户的密码字段
> [!TIP]

Feat o auth2 logout ce

---

api/swagger.json
api/swagger.yaml
internal/dms/biz/repo_fields.go
internal/dms/service/project.go
pkg/dms-common/api/dms/v1/project.go

link https://github.com/actiontech/dms-ee/pull/427
合并到main-ee 以供dms-sdk更新

Add filter to filter project by desc

---

Makefile

https://github.com/actiontech/sqle-ee/issues/2106

1. Add the edition suffix only when there is a tag. 2. Extract variables to make the statement more understandable.

---

internal/apiserver/conf/options.go
internal/dms/biz/db_service.go
internal/dms/biz/plugin.go
internal/dms/service/cloudbeaver.go
internal/dms/service/db_service.go
internal/dms/service/plugin.go
internal/dms/service/service.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go
pkg/dms-common/api/dms/v1/plugin.go

issue：https://github.com/actiontech/dms/issues/219
优化插件配置方式，移除config.yaml中的配置，改为接口从dms plugin中获取（当前是sqle和provision实现数据库扩展插件参数接口）
1、插件的自动化配置需调整
2、数据源类型可选项由启用的插件决定而不是配置
3、固定logo文件路径，不再手动配置
兼容旧版本（若使用了自定义的logo文件且不在默认路径下，需要手动调整至 {dms path}/static/logo/）

Optimize plugin ce

---

Makefile

https://github.com/actiontech/sqle-ee/issues/2106
assign in @LordofAvernus

remove leading space from line

---

internal/dms/biz/db_service.go
pkg/dms-common/pkg/config/validator.go

https://github.com/actiontech/sqle/issues/2810
创建数据源前对数据源名称进行校验
> [!TIP]

fix dbService name can be invalid ce

---

Makefile
build/dms_sqle_provision.spec

- issue
https://github.com/actiontech/sqle-ee/issues/2116

feat: dms package jdk

---

Makefile
api/dms/service/v1/data_export_task.go
api/swagger.json
api/swagger.yaml
internal/dms/service/data_export_workflow.go
internal/dms/storage/model/model.go
internal/pkg/cloudbeaver/graphql.go

issue:
https://github.com/actiontech/sqle/issues/2860
1.数据导出新增规则审核报错提示
2.cb操作日志接口日志新增规则审核报错提示
3.规则报错后cb不下发sql
link https://github.com/actiontech/sqle/pull/2879

Add audit result error result ce

---

internal/dms/storage/model/model.go

- https://github.com/actiontech/dms-ee/issues/444
- 工作台中无法显示数据源

fix: increase field length limit

---

internal/pkg/cloudbeaver/graphql.go

修复当cb审核PassRate为1时无法返回含有执行报错规则
link https://github.com/actiontech/sqle/pull/2885

fix: cb sql audit missing  execution rule error result

---

build/dms_sqle_provision.spec

- issue: https://github.com/actiontech/dms-ee/issues/439
- 需要验证经过gocd打包后的RPM包

feat: make jdk support neo4j

---

internal/dms/biz/cloudbeaver.go
internal/pkg/cloudbeaver/model/models_gen.go
internal/pkg/cloudbeaver/resolver/executor_gen.go
internal/pkg/cloudbeaver/schema/service.core.graphqls

issue: https://github.com/actiontech/sqle/issues/2884
cb执行审核新增返回字段，返回执行报错的规则

Fix missing return rule error

---

internal/dms/biz/cloudbeaver.go

issue： https://github.com/actiontech/dms/issues/365
描述: 
修复cb缺失OceanBase MySQL的数据源问题

fix: cb connect ob mysql

---

internal/dms/service/db_service.go

issue: https://github.com/actiontech/sqle/issues/2851

fix: change updateConnectionStatus uid to pkgConst.UIDOfUserAdmin

---

internal/dms/service/db_service.go

issue: https://github.com/actiontech/sqle/issues/2851

fix: lastConnectionStatus nil panic

---

internal/dms/biz/user.go
internal/dms/service/user.go
pkg/dms-common/api/dms/v1/user.go

issue: https://github.com/actiontech/sqle-ee/issues/2208

fix: update two factor enabled failed

---

api/swagger.yaml

issue: https://github.com/actiontech/sqle-ee/issues/2208

fix: update swagger.yaml add TwoFactorEnabled

---

internal/dms/biz/sms_configuration.go
internal/dms/service/service.go

- 实现双因素短信对接服务
- issus: https://github.com/actiontech/dms-ee/issues/478

feat: implement SMS service integration

---

internal/dms/biz/cloudbeaver.go

issue: https://github.com/actiontech/sqle/issues/2936
changes:
1. 修复了工作台SQL执行统计数据错误的bug
2. 修复了未记录工作台上执行的SQL的执行时间以及返回行数的值的问题。
3. 使用AI增加了注释
4. 增加了TODO：寻找一名铲屎官来优化一下这个屎山

fix two bugs in sql workbench

---

build/dms_sqle_provision.spec

issue: https://github.com/actiontech/sqle-ee/issues/2254

fix: add SQLE_JAVA_HOME env

---

build/dms_sqle_provision.spec

(cherry picked from commit 7bcecd8841516ae57543d1bff606ce1e6c32a68f)

cherry-pick: add SQLE_JAVA_HOME env

---

api/dms/service/v1/configuration.go
api/swagger.json
api/swagger.yaml
internal/dms/biz/oauth2_configuration.go
internal/dms/biz/oauth2_configuration_ce.go
internal/dms/service/configuration.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go

https://github.com/actiontech/sqle-ee/issues/2265
assign in @ColdWaterLW

api(OAuth2): 添加登录权限表达式功能接口

---

.github/workflows/pr-agent.yml
.pr-agent.toml

link https://github.com/actiontech/sqle/pull/2979
https://github.com/actiontech/sqle/issues/2977

add configuration for pr-agent

---

.github/workflows/pr-agent.yml

actiontech/sqle/issues/2977
修复配置文件的格式错误
link https://github.com/actiontech/sqle/pull/2984

fix format error

---

build/dms_sqle_provision.spec

issue: https://github.com/actiontech/sqle-ee/issues/2307
link https://github.com/actiontech/sqle/pull/3000

cherry-pick: remove env SQLE_JAVA_HOME

---

internal/apiserver/service/dms_controller.go
internal/apiserver/service/dms_controller_v2.go
internal/apiserver/service/router.go
internal/dms/biz/db_service.go
internal/dms/biz/repo_fields.go
internal/dms/service/db_service.go
internal/dms/storage/convert.go
internal/dms/storage/db_service.go
internal/dms/storage/model/model.go

issue: https://github.com/actiontech/sqle/issues/3008
v2 - 获取项目数据源列表实现
assign in @winfredLIN

Global resources ce

---

internal/dms/biz/project.go

fix init dms failed, because init logic in a tx, so cannot get business in mysql
issue: https://github.com/actiontech/sqle/issues/3008
assign in @littleniannian

fix(init): create business failed due to get it in tx

---

api/dms/service/v1/resource_overview.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go

https://github.com/actiontech/sqle-ee/issues/2321
1. add resource overview http api group interfaces' definition

api definition for resource overview api group

---

internal/apiserver/service/dms_controller.go
internal/dms/service/configuration.go

https://github.com/actiontech/sqle-ee/issues/2279
assign in @LordofAvernus

refactor(dms): 后端通道注销同步处理

---

internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
internal/dms/service/resource_overview_ce.go

https://github.com/actiontech/sqle-ee/issues/2321
https://github.com/actiontech/sqle-ee/issues/2321#issuecomment-2801248655
- Implement GetResourceOverviewResourceTypeDistribution method in DMSController
- Add corresponding route in APIServer
- Update DMSService to support the new endpoint

feat(resource-overview): add resource type distribution endpoint

---

.github/workflows/pr-agent.yml
.pr_agent.toml

link https://github.com/actiontech/sqle/pull/3019

update pr agent configuration

---

internal/apiserver/service/dms_controller.go
internal/dms/biz/oauth2_configuration.go
internal/dms/biz/oauth2_configuration_ce.go
internal/dms/service/configuration.go

https://github.com/actiontech/dms-ee/issues/627
___
- 支持登录后重定向原页面
- 新增State提取目标路径逻辑
- 调整函数参数传递方式
- 增强日志调试信息
___
```mermaid
flowchart LR
A["dms_controller.go 处理用户请求"] --> B["oauth2_configuration.go 处理重定向数据"]
B --> C["oauth2_configuration_ce.go 生成链接参数"]
C --> D["configuration.go 调用链接生成"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>dms_controller.go</strong><dd><code>更新OAuth2入口和回调处理</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

feat(oauth2): support redirect to original page after login

---

internal/dms/service/member.go
internal/dms/storage/member_group.go

issue: https://github.com/actiontech/sqle/issues/3098
___
- 新增map检查重复权限，确保权限不被重复显示
- 优化成员组中空权限时的删除逻辑
- 采用事务处理确保删除操作的原子性
___
```mermaid
flowchart LR
A["新增map检查重复权限"] --> B["成员列表去重"]
C["优化删除空权限逻辑"] --> D["事务确保原子性"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>member.go</strong><dd><code>添加成员权限去重逻辑</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix: member&membergroup permission

---

internal/dms/biz/cloudbeaver.go

fix: https://github.com/actiontech/dms/issues/515
___
- 修改用户存在性检测逻辑
- 避免模糊查询导致误判
- 新增精确检测 helper 方法
___
```mermaid
flowchart LR
A["调用 createUserIfNotExist"]
B["调用 checkCloudBeaverUserExist"]
A -- "判断用户是否存在" --> B
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>cloudbeaver.go</strong><dd><code>优化用户存在性检测并修复更新逻辑</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix(cloudbeaver): optimize cloudbeaver user existence check

---

internal/dms/biz/data_export_workflow.go
internal/dms/biz/data_export_workflow_ce.go
internal/dms/service/data_export_workflow.go
internal/dms/storage/workflow.go

issue: https://github.com/actiontech/sqle-ee/issues/2516
___
- 新增项目级数据导出接口方法
- 修改工作流列表函数参数（添加 projectUid）
- 更新 API 调用以传递项目 ID
- 实现项目和 DB 服务联合过滤
___
```mermaid
flowchart LR
A["internal/dms/biz/data_export_workflow.go 接口扩展"] --> B["新增项目级方法"]
C["internal/dms/biz/data_export_workflow_ce.go 修改参数"] --> D["添加 projectUid 参数"]
E["internal/dms/service/data_export_workflow.go 更新调用"] --> D
F["internal/dms/storage/workflow.go 新增实现"] --> B
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>data_export_workflow.go</strong><dd><code>新增项目级数据导出接口</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix: failed to list data export workflow when without global view permission

---

api/dms/service/v1/business_tag.go
api/swagger.json
api/swagger.yaml
internal/dms/biz/business_tag.go
internal/dms/service/business_tag.go
internal/dms/service/project.go
internal/dms/service/user.go
internal/dms/storage/business_tag.go
pkg/dms-common/api/dms/v1/user.go
pkg/dms-common/api/dms/v2/project.go

issue: 
- https://github.com/actiontech/dms/issues/509
- https://github.com/actiontech/dms-ee/issues/648
___
- 支持业务标签、项目和用户的模糊关键字查询
- 更新查询结构体和调用参数，加入 FuzzyKeyword 字段
- 修改 Swagger 文档，反映接口变更
___
```mermaid
flowchart LR
node1["新增 FuzzyKeyword 字段"]
node2["业务标签查询更新"]
node3["项目查询更新"]
node4["用户查询更新"]
node5["更新 Swagger 文档"]
node1 -- "用于" --> node2
node1 -- "用于" --> node3
node1 -- "用于" --> node4
node1 -- "同步更新" --> node5
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>5 files</summary><table>
<tr>
<td><strong>business_tag.go</strong><dd><code>为业务标签请求添加模糊搜索参数</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

feat: add fuzzword for list projects users business tag

---

api/dms/service/v1/user.go
api/swagger.json
api/swagger.yaml
internal/dms/biz/user.go
internal/dms/service/user.go
internal/dms/storage/convert.go
internal/dms/storage/model/model.go
pkg/dms-common/api/dms/v1/user.go

- 为了实现用户选择不同系统的功能，用户实体中添加系统字段
- issue: https://github.com/actiontech/sqle/issues/3133
___
- 添加 UserSystem 字段以支持用户系统配置
- 更新业务逻辑处理和数据转换以兼容新字段
- 完善 Swagger 文档描述和枚举定义
___
```mermaid
flowchart LR
A["UpdateUser请求结构更新"] --> B["新增System字段"]
B --> C["业务层及存储层数据转换修改"]
C --> D["Swagger文档与API更新"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table>
<tr>
<td><strong>user.go</strong><dd><code>新增请求中的System字段和UserSystem枚举</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

feat: add system prop for user config

---

internal/sql_workbench/client/sql_workbench_client.go
internal/sql_workbench/service/sql_workbench_service.go

assign in @LordofAvernus 
https://github.com/actiontech/sqle/issues/3133
- 修复对接odc后oracle连接不上的问题，需要传递`serviceName`
> [!TIP]
___
- 新增 Oracle 数据库连接所需 serviceName 支持
- 修改登录与 Cookie 获取方法，返回公钥
- 提取构建数据源基础信息的公共方法
- 更新创建与更新数据源请求，传递 serviceName 参数
___
```mermaid
flowchart LR
A["修改 getUserCookie 方法"]
B["新增 ServiceName 字段处理"]
C["提取 buildDatasourceBaseInfo 方法"]
D["更新 buildCreateDatasourceRequest 方法"]
E["更新 buildUpdateDatasourceRequest 方法"]
A -- "返回公钥信息" --> B
B -- "Oracle 特殊处理" --> C
C -- "构建基础数据源信息" --> D
C -- "构建基础数据源信息" --> E
```
<table><thead><tr><th></th><th …

fix: oracle connect failed

---

internal/sql_workbench/service/sql_workbench_service.go

assign in @LordofAvernus 
https://github.com/actiontech/sqle/issues/3133
- 修复创建odc用户存在DMS-前缀的问题
> [!TIP]
___
- 修复创建用户时用户名配置错误
- 调整同步数据源时用户名生成逻辑
- 修改登录时传递用户名的调用方式
___
```mermaid
flowchart LR
A["修改 createSqlWorkbenchUser 中用户名赋值"] --> B["调整 syncDatasources 中 Cookie 获取调用"]
B --> C["修改 getUserCookie 中登录调用参数"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>sql_workbench_service.go</strong><dd><code>修正 odc 用户名相关逻辑，去除多余前缀</code>&nbsp; &nbsp; &nbsp; …

fix: odc username remove DMS- prefix

---

api/dms/service/v1/data_export_workflow.go
api/swagger.json
api/swagger.yaml
internal/apiserver/service/dms_controller.go
internal/apiserver/service/router.go
internal/dms/biz/data_export_workflow.go
internal/dms/service/data_export_workflow.go
internal/dms/storage/workflow.go

https://github.com/actiontech/sqle/issues/3133
- 增加全局数据导出工单接口
> [!TIP]
___
- 新增全局数据导出工单接口
- 调整请求参数与返回字段(ProjectName)
- 完善swagger文档定义
- 增加数据库查询辅助方法
___
```mermaid
flowchart LR
A["新增API接口"]
B["新增控制器方法 ListAllDataExportWorkflows"]
C["更新路由配置"]
D["补充业务逻辑获取 ProjectName"]
E["更新Swagger文档"]
A -- "调用新接口" --> B
B -- "配置路由" --> C
C -- "执行业务逻辑" --> D
D -- "文档更新" --> E
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>6 files</summary><table>
<tr> …

feat: list all data export workflows
